FROM alpine:latest

WORKDIR /home/node/app

COPY package*.json ./

RUN apk add --no-cache nodejs npm \
    && NODE_ENV="production" npm ci --omit=dev \
    && addgroup -S pairdrop \
    && adduser -S pairdrop -G pairdrop

COPY --chown=pairdrop:pairdrop . .

ENV NODE_ENV="production"

USER pairdrop

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 \
    CMD wget --quiet --tries=1 --spider http://localhost:3000 || exit 1

ENTRYPOINT ["npm", "start"]
